# COLORS
CATPPUCCIN_MOCHA_GREEN=0xffa6da95
CATPPUCCIN_MOCHA_MANTLE=0xff181825
CATPPUCCIN_MOCHA_BASE=0xff1e1e2e
CATPPUCCIN_MOCHA_SURFACE_0=0xff363a4f
export WHITE=0xffffffff

export SYSTEM_BG_COLOR=$CATPPUCCIN_MOCHA_BASE
export SYSTEM_SURFACE_COLOR=$CATPPUCCIN_MOCHA_SURFACE_0
export SYSTEM_ACCENT_COLOR=$CATPPUCCIN_MOCHA_GREEN

# FONTS
MACOS="SF Pro:Semibold:15.0"
JETBRAINS="JetBrainsMono Nerd Font Mono:Regular:13.0"
export SYSTEM_FONT=$JETBRAINS
